"""init command implementation for the AI Artifact Validator CLI.

Generates a default .aav.yaml configuration file with commented documentation.

Requirements: 16.1, 16.10
"""

from __future__ import annotations

from pathlib import Path

import click
from rich.console import Console

# Default config template with documentation comments
DEFAULT_CONFIG_TEMPLATE = """\
# .aav.yaml - AI Artifact Risk Validator Configuration
# Generated by: ai-artifact-validator init
version: "1.0"

# Scanner control
scanners:
  enabled:
    - SecretScan
    - InjectionDet
    - PermAudit
    - TokenAnalyzer
    - SchemaValid
    - DepScan
    - QualityLint
    - ProvenanceChk
    - BiasDetector
    - ComposeAnalyze
    - PortabilityChk
    - ComplianceAudit
    - CodeAudit
  disabled: []

# Severity and gate configuration
severity:
  threshold: 1  # Minimum severity to report (1-10)
  gate_overrides: {}

# File filtering
files:
  include: []
  exclude:
    - "node_modules/**"
    - ".git/**"
    - "__pycache__/**"
    - "*.pyc"
  max_size_bytes: 10485760  # 10 MB

# Performance
performance:
  parallel_files: 4
  parallel_scanners: 4
  cache_dir: ".aav_cache"

# Suppressions
# Add entries to suppress known false positives:
# suppressions:
#   - risk_id: P-S3
#     file_pattern: "tests/fixtures/**"
#     reason: "Test fixtures intentionally contain mock secrets"
suppressions: []

# Custom artifact classification patterns
# custom_patterns:
#   prompt:
#     - "*.prompt.txt"
#   instruction:
#     - ".cursor/*.md"
custom_patterns: {}

# Plugin directories for custom scanners
# plugins:
#   directories:
#     - "./custom-scanners/"
plugins:
  directories: []

# Semantic (embedding-based) analysis
# Requires: pip install ai-artifact-risk-validator[ml]
semantic:
  enabled: true                   # Set to false to disable semantic analysis
  model_name: "all-MiniLM-L6-v2" # Sentence-transformer model
  threshold: 0.55                 # Similarity threshold for semantic matches (0.0-1.0)
"""


@click.command("init")
@click.option(
    "--path",
    "-p",
    "target_path",
    type=click.Path(exists=True, file_okay=False, resolve_path=True),
    default=".",
    help="Target directory for .aav.yaml (default: current directory).",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help="Overwrite existing .aav.yaml file.",
)
def init(target_path: str, force: bool) -> None:
    """Generate a default .aav.yaml configuration file."""
    console = Console()
    target_dir = Path(target_path)
    config_file = target_dir / ".aav.yaml"

    if config_file.exists() and not force:
        console.print(
            f"[yellow]Configuration file already exists:[/yellow] {config_file}\n"
            "[dim]Use --force to overwrite.[/dim]"
        )
        raise SystemExit(1)

    config_file.write_text(DEFAULT_CONFIG_TEMPLATE, encoding="utf-8")
    console.print(f"[green]Created configuration file:[/green] {config_file}")
