"""Unit tests for additional dep_scan parser functions that are currently untested.

Covers: _parse_pipfile_lock, _parse_cargo_lock, _parse_go_sum,
_parse_yarn_lock, _parse_pnpm_lock, _version_less_than
"""

from __future__ import annotations

import pytest

from ai_artifact_risk_validator.models import ArtifactType
from ai_artifact_risk_validator.scanners.dep_scan import (
    DepScanScanner,
    _parse_cargo_lock,
    _parse_go_sum,
    _parse_pipfile_lock,
    _parse_pnpm_lock,
    _parse_yarn_lock,
)


class TestParsePipfileLock:
    """Tests for Pipfile.lock parser."""

    def test_valid_pipfile_lock(self):
        """Parses a valid Pipfile.lock with dependencies."""
        content = """{
    "_meta": {"hash": {"sha256": "abc"}},
    "default": {
        "requests": {"version": "==2.28.0"},
        "flask": {"version": "==2.3.2"}
    },
    "develop": {
        "pytest": {"version": "==7.4.0"}
    }
}"""
        deps = _parse_pipfile_lock(content)
        assert len(deps) == 3
        names = {d["name"] for d in deps}
        assert "requests" in names
        assert "flask" in names
        assert "pytest" in names
        assert all(d["pinned"] is True for d in deps)
        assert all(d["operator"] == "==" for d in deps)

    def test_pipfile_lock_no_version_prefix(self):
        """Dependencies without == prefix."""
        content = """{
    "default": {
        "mypackage": {"version": "1.0.0"}
    }
}"""
        deps = _parse_pipfile_lock(content)
        assert len(deps) == 1
        assert deps[0]["version"] == "1.0.0"
        assert deps[0]["pinned"] is True

    def test_pipfile_lock_empty_version(self):
        """Dependencies with empty version string."""
        content = """{
    "default": {
        "mypackage": {"version": ""}
    }
}"""
        deps = _parse_pipfile_lock(content)
        assert len(deps) == 1
        assert deps[0]["version"] is None
        assert deps[0]["pinned"] is False

    def test_pipfile_lock_invalid_json(self):
        """Invalid JSON returns empty list."""
        deps = _parse_pipfile_lock("not json{{{")
        assert deps == []

    def test_pipfile_lock_non_dict_root(self):
        """Non-dict root returns empty list."""
        deps = _parse_pipfile_lock("[1, 2, 3]")
        assert deps == []

    def test_pipfile_lock_non_dict_section(self):
        """Non-dict section value is skipped."""
        content = '{"default": "invalid"}'
        deps = _parse_pipfile_lock(content)
        assert deps == []

    def test_pipfile_lock_non_dict_info(self):
        """Non-dict package info is skipped."""
        content = '{"default": {"pkg": "not_a_dict"}}'
        deps = _parse_pipfile_lock(content)
        assert deps == []


class TestParseCargoLock:
    """Tests for Cargo.lock parser."""

    def test_valid_cargo_lock(self):
        """Parses a valid Cargo.lock."""
        content = """# This file is automatically generated by Cargo.
[[package]]
name = "serde"
version = "1.0.188"

[[package]]
name = "tokio"
version = "1.32.0"
"""
        deps = _parse_cargo_lock(content)
        assert len(deps) == 2
        assert deps[0]["name"] == "serde"
        assert deps[0]["version"] == "1.0.188"
        assert deps[0]["pinned"] is True
        assert deps[1]["name"] == "tokio"
        assert deps[1]["version"] == "1.32.0"

    def test_empty_cargo_lock(self):
        """Empty Cargo.lock returns empty list."""
        deps = _parse_cargo_lock("")
        assert deps == []

    def test_cargo_lock_no_packages(self):
        """Cargo.lock with no package sections."""
        content = "# Just a comment\n"
        deps = _parse_cargo_lock(content)
        assert deps == []


class TestParseGoSum:
    """Tests for go.sum parser."""

    def test_valid_go_sum(self):
        """Parses a valid go.sum file."""
        content = """github.com/gin-gonic/gin v1.9.1 h1:4+fr/el88TOO3ewCmQr8cx/CtZ/umlIRIs5M4NTNjf8=
github.com/gin-gonic/gin v1.9.1/go.mod h1:hPrL/0KcuDCXZPGWi1BJELQQM=
github.com/go-playground/validator/v10 v10.15.0 h1:oVHQKFJWc=
"""
        deps = _parse_go_sum(content)
        assert len(deps) == 2
        names = {d["name"] for d in deps}
        assert "github.com/gin-gonic/gin" in names
        assert "github.com/go-playground/validator/v10" in names
        # Check deduplication works (gin appears twice)
        gin_deps = [d for d in deps if "gin" in d["name"]]
        assert len(gin_deps) == 1

    def test_go_sum_empty(self):
        """Empty go.sum returns empty list."""
        deps = _parse_go_sum("")
        assert deps == []

    def test_go_sum_blank_lines_skipped(self):
        """Blank lines are skipped."""
        content = "\n\n\ngithub.com/pkg/errors v0.9.1 h1:abc=\n\n"
        deps = _parse_go_sum(content)
        assert len(deps) == 1
        assert deps[0]["name"] == "github.com/pkg/errors"

    def test_go_sum_short_lines_skipped(self):
        """Lines with fewer than 3 parts are skipped."""
        content = "github.com/pkg\n"
        deps = _parse_go_sum(content)
        assert deps == []


class TestParseYarnLock:
    """Tests for yarn.lock parser."""

    def test_valid_yarn_lock(self):
        """Parses a valid yarn.lock file."""
        content = """# yarn lockfile v1

"express@^4.18.0":
  version "4.18.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"

"lodash@^4.17.0":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
"""
        deps = _parse_yarn_lock(content)
        assert len(deps) == 2
        names = {d["name"] for d in deps}
        assert "express" in names
        assert "lodash" in names

    def test_yarn_lock_empty(self):
        """Empty yarn.lock returns empty list."""
        deps = _parse_yarn_lock("")
        assert deps == []


class TestParsePnpmLock:
    """Tests for pnpm-lock.yaml parser."""

    def test_valid_pnpm_lock(self):
        """Parses a valid pnpm-lock.yaml file."""
        content = """lockfileVersion: '6.0'

packages:

  /express@4.18.2:
    resolution: {integrity: sha512-...}
    dependencies: {}

  /lodash@4.17.21:
    resolution: {integrity: sha512-...}
"""
        deps = _parse_pnpm_lock(content)
        assert len(deps) >= 1
        names = {d["name"] for d in deps}
        # Should detect at least some packages
        assert all(d["pinned"] is True for d in deps)

    def test_pnpm_lock_empty(self):
        """Empty pnpm-lock returns empty list."""
        deps = _parse_pnpm_lock("")
        assert deps == []


class TestDepScanScannerParsers:
    """Integration tests for the DepScan scanner with different file types."""

    @pytest.fixture
    def scanner(self) -> DepScanScanner:
        return DepScanScanner()

    def test_scan_pipfile_lock_content(self, scanner: DepScanScanner):
        """Scanner processes Pipfile.lock content."""
        content = """{
    "default": {
        "requests": {"version": "==2.28.0"},
        "flask": {"version": "==2.3.2"}
    }
}"""
        findings = scanner.scan(content, ArtifactType.MCP, "Pipfile.lock")
        # Should not crash; may or may not produce findings
        assert isinstance(findings, list)

    def test_scan_cargo_lock_content(self, scanner: DepScanScanner):
        """Scanner processes Cargo.lock content."""
        content = """[[package]]
name = "serde"
version = "1.0.188"

[[package]]
name = "tokio"
version = "1.32.0"
"""
        findings = scanner.scan(content, ArtifactType.PLUGIN, "Cargo.lock")
        assert isinstance(findings, list)

    def test_scan_go_sum_content(self, scanner: DepScanScanner):
        """Scanner processes go.sum content."""
        content = "github.com/gin-gonic/gin v1.9.1 h1:abc=\n"
        findings = scanner.scan(content, ArtifactType.MCP, "go.sum")
        assert isinstance(findings, list)

    def test_scan_yarn_lock_content(self, scanner: DepScanScanner):
        """Scanner processes yarn.lock content."""
        content = """"express@^4.18.0":
  version "4.18.2"
"""
        findings = scanner.scan(content, ArtifactType.HOOK, "yarn.lock")
        assert isinstance(findings, list)

    def test_scan_pnpm_lock_content(self, scanner: DepScanScanner):
        """Scanner processes pnpm-lock.yaml content."""
        content = """lockfileVersion: '6.0'
packages:
  /express@4.18.2:
    resolution: {integrity: sha512-...}
"""
        findings = scanner.scan(content, ArtifactType.SKILL, "pnpm-lock.yaml")
        assert isinstance(findings, list)

    def test_scan_package_json_with_wildcards(self, scanner: DepScanScanner):
        """Scanner flags wildcard versions in package.json."""
        content = """{
    "dependencies": {
        "express": "*",
        "lodash": "latest"
    }
}"""
        findings = scanner.scan(content, ArtifactType.PLUGIN, "package.json")
        # Should detect wildcard/unpinned versions
        assert isinstance(findings, list)

    def test_scan_requirements_with_unpinned(self, scanner: DepScanScanner):
        """Scanner flags unpinned dependencies in requirements.txt."""
        content = """requests>=2.28.0
flask
numpy==1.24.0
"""
        findings = scanner.scan(content, ArtifactType.SKILL, "requirements.txt")
        assert isinstance(findings, list)
