"""Risk definitions for Agent artifacts (A-S1 through A-R3).

Contains 17 risks covering security, performance, and reliability categories
for agent configurations and definitions.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (A-S1 to A-S9) =====
    RiskDefinition(
        id="A-S1",
        title="Unrestricted Tool Access",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Agent is configured with unrestricted access to all tools without permission boundaries.",
        examples=["Agent with wildcard tool permissions", "No tool allowlist configured"],
        mitigation=[
            "Implement tool allowlists",
            "Define explicit permission boundaries",
            "Apply least-privilege access",
        ],
        detection_mechanisms=["Tool permission scope analysis", "Wildcard permission detection"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-250"],
    ),
    RiskDefinition(
        id="A-S2",
        title="Excessive Autonomous Action Scope",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Agent can perform destructive or irreversible actions without human-in-the-loop confirmation.",
        examples=[
            "File deletion without confirmation",
            "Database modification without approval gate",
        ],
        mitigation=[
            "Add confirmation gates for destructive actions",
            "Implement human-in-the-loop for high-risk operations",
            "Set action boundaries",
        ],
        detection_mechanisms=["Destructive action capability analysis", "Confirmation gate audit"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-862"],
    ),
    RiskDefinition(
        id="A-S3",
        title="Unsafe Code Execution Capability",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Agent has capability to execute arbitrary code without sandboxing or safety controls.",
        examples=["Unsandboxed code interpreter tool", "Direct shell access without restrictions"],
        mitigation=[
            "Sandbox code execution",
            "Implement allowlisted commands",
            "Add output filtering",
        ],
        detection_mechanisms=["Code execution capability detection", "Sandbox configuration audit"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-94"],
    ),
    RiskDefinition(
        id="A-S4",
        title="Agent Goal Manipulation Vulnerability",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Agent's goal or objective can be manipulated via injected content in its operating environment.",
        examples=[
            "Goal override via document content",
            "Task hijacking through crafted user input",
        ],
        mitigation=[
            "Protect goal definitions from external input",
            "Validate task sources",
            "Implement goal integrity checks",
        ],
        detection_mechanisms=["Goal protection analysis", "Input isolation verification"],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-284"],
    ),
    RiskDefinition(
        id="A-S5",
        title="Multi-Agent Trust Boundary Violation",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Agent trusts messages from other agents without verification, enabling lateral injection attacks.",
        examples=[
            "Accepting unvalidated tool results from sub-agents",
            "No message authentication between agents",
        ],
        mitigation=[
            "Validate inter-agent messages",
            "Implement trust boundaries",
            "Add message authentication",
        ],
        detection_mechanisms=["Trust boundary analysis", "Inter-agent communication audit"],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-306"],
    ),
    RiskDefinition(
        id="A-S6",
        title="Uncontrolled Resource Access",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Agent can access sensitive resources (databases, APIs, files) without access control validation.",
        examples=[
            "Direct database access without role check",
            "API access without scope limitation",
        ],
        mitigation=[
            "Implement resource access controls",
            "Validate access tokens per operation",
            "Add resource allowlists",
        ],
        detection_mechanisms=["Resource access scope analysis", "Access control verification"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-863"],
    ),
    RiskDefinition(
        id="A-S7",
        title="Dangerous Tool Combination",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Agent has access to a combination of tools that together enable dangerous operations not intended individually.",
        examples=[
            "File read + network access enabling data exfiltration",
            "Code exec + filesystem enabling persistent backdoor",
        ],
        mitigation=[
            "Audit tool combinations for emergent risks",
            "Implement tool interaction policies",
            "Restrict dangerous combinations",
        ],
        detection_mechanisms=["Tool combination risk analysis", "Capability composition audit"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-269"],
    ),
    RiskDefinition(
        id="A-S8",
        title="Unverified Agent Source",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Agent definition lacks provenance verification, making it susceptible to supply chain attacks.",
        examples=["Agent from unverified marketplace", "No signature on agent configuration"],
        mitigation=[
            "Verify agent source and author",
            "Implement signature verification",
            "Use trusted agent registries",
        ],
        detection_mechanisms=["Provenance metadata validation", "Signature verification"],
        scanner_modules=[ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-345"],
    ),
    RiskDefinition(
        id="A-S9",
        title="Missing Agent Integrity Hash",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Agent configuration lacks integrity hash, making tampering detection impossible.",
        examples=["No content hash in agent metadata", "Missing checksum for agent bundle"],
        mitigation=[
            "Add integrity hashes to agent configs",
            "Implement tamper detection",
            "Version control all agent files",
        ],
        detection_mechanisms=["Integrity hash presence check", "Content hash validation"],
        scanner_modules=[ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-354"],
    ),
    # ===== Performance Risks (A-P1 to A-P5) =====
    RiskDefinition(
        id="A-P1",
        title="Excessive Agent Initialization Cost",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Agent requires expensive initialization (loading large models, fetching remote configs) that degrades startup performance.",
        examples=[
            "Loading full model weights on every invocation",
            "Fetching remote configuration on each request",
        ],
        mitigation=[
            "Implement lazy initialization",
            "Cache initialization results",
            "Use lightweight startup path",
        ],
        detection_mechanisms=["Initialization complexity analysis", "Startup cost estimation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="A-P2",
        title="Excessive Agent System Prompt Size",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.PERFORMANCE,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Agent system prompt is excessively large, consuming significant context window budget.",
        examples=[
            "Agent system prompt over 8000 tokens",
            "Detailed instructions exceeding model limits",
        ],
        mitigation=[
            "Compress system prompt",
            "Use hierarchical instruction loading",
            "Implement lazy instruction fetch",
        ],
        detection_mechanisms=[
            "Token count analysis of system prompt",
            "Budget threshold comparison",
        ],
        scanner_modules=[ScannerModule.TOKEN_ANALYZER],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="A-P3",
        title="Tool Description Token Bloat",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Agent's tool descriptions consume excessive tokens, reducing available context for conversation.",
        examples=["20 tools each with 500-token descriptions", "Redundant parameter documentation"],
        mitigation=[
            "Compress tool descriptions",
            "Use selective tool loading",
            "Implement tool pagination",
        ],
        detection_mechanisms=["Aggregate tool description token count", "Per-tool token analysis"],
        scanner_modules=[ScannerModule.TOKEN_ANALYZER],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="A-P4",
        title="Unbounded Conversation History",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.PERFORMANCE,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Agent lacks conversation history management, risking context window overflow.",
        examples=[
            "No history truncation policy",
            "Accumulating full history without summarization",
        ],
        mitigation=[
            "Implement history truncation",
            "Add summarization for long conversations",
            "Set maximum history tokens",
        ],
        detection_mechanisms=[
            "History management configuration check",
            "Truncation policy detection",
        ],
        scanner_modules=[ScannerModule.TOKEN_ANALYZER],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="A-P5",
        title="Agent Composition Latency Risk",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.PERFORMANCE,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Agent participates in multi-agent compositions that amplify latency through sequential dependencies.",
        examples=["Five-agent sequential chain", "Blocking dependencies between agent steps"],
        mitigation=[
            "Parallelize independent agent steps",
            "Reduce chain depth",
            "Add timeout boundaries",
        ],
        detection_mechanisms=["Composition chain analysis", "Sequential dependency detection"],
        scanner_modules=[ScannerModule.COMPOSE_ANALYZE],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Reliability Risks (A-R1 to A-R3) =====
    RiskDefinition(
        id="A-R1",
        title="Missing Fallback Behavior",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.RELIABILITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Agent lacks defined fallback behavior for tool failures or model errors.",
        examples=[
            "No retry logic for failed tool calls",
            "Missing error handling for API timeouts",
        ],
        mitigation=[
            "Define fallback behaviors",
            "Implement retry with exponential backoff",
            "Add graceful degradation paths",
        ],
        detection_mechanisms=["Fallback configuration detection", "Error handling audit"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="A-R2",
        title="Infinite Loop Risk in Agent Planning",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.RELIABILITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Agent planning loop lacks termination conditions, risking infinite execution.",
        examples=["No maximum iteration count", "Missing convergence check in planning loop"],
        mitigation=[
            "Set maximum iteration limits",
            "Add convergence detection",
            "Implement timeout boundaries",
        ],
        detection_mechanisms=["Loop termination condition check", "Iteration limit detection"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="A-R3",
        title="Missing Agent Health Monitoring",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.RELIABILITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Agent lacks health monitoring, making it difficult to detect degraded performance or failures.",
        examples=["No metrics collection", "Missing heartbeat mechanism"],
        mitigation=[
            "Add health check endpoints",
            "Implement metrics collection",
            "Configure alerting thresholds",
        ],
        detection_mechanisms=["Monitoring configuration check", "Observability audit"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Output Handling Risks (OH-S1 to OH-S3) =====
    RiskDefinition(
        id="OH-S1",
        title="Unvalidated Agent Output Passed to Downstream Executor",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "Agent output is forwarded to a code executor, shell, or tool invocation "
            "without first validating or sanitizing it. If the LLM produces malicious "
            "or unexpected content, this creates a secondary injection path."
        ),
        examples=[
            "output = agent.run(input); exec(output)",
            "Agent response JSON parsed and keys used as subprocess arguments without validation",
            "Tool invocation payload built directly from agent string output",
        ],
        mitigation=[
            "Validate agent output with a schema or allowlist before forwarding",
            "Treat LLM output as untrusted user input — apply the same input validation rules",
            "Use structured output formats (JSON Schema) and reject non-conforming responses",
            "Add a human-in-the-loop gate for high-risk downstream operations",
        ],
        detection_mechanisms=[
            "Regex: agent/LLM result variable used directly as exec/subprocess/tool arg",
            "AST taint: chain from LLM call to code-execution or network sink",
        ],
        scanner_modules=[ScannerModule.INJECTION_DET, ScannerModule.TAINT_TRACK],
        owasp_refs=["LLM06:2025 Excessive Agency", "LLM02:2025 Sensitive Information Disclosure"],
        cwe_refs=["CWE-78", "CWE-74"],
    ),
    RiskDefinition(
        id="OH-S2",
        title="Agent Output Contains Secret Material",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description=(
            "The agent definition or its output-handling code may cause it to surface "
            "secret material (API keys, tokens, credentials) in its responses. This "
            "can occur when the agent echoes environment variables or config values."
        ),
        examples=[
            "Agent instructed to include debug context containing environment variables",
            "Output formatter includes raw config dict without redacting secrets",
        ],
        mitigation=[
            "Apply an output-redaction pass before returning agent responses",
            "Never inject secret values into agent context or output templates",
            "Use placeholder tokens for secret values in agent definitions",
        ],
        detection_mechanisms=[
            "Secret-pattern regex on agent output-handler code",
            "Detection of os.environ / config references in output-formatting code",
        ],
        scanner_modules=[ScannerModule.SECRET_SCAN, ScannerModule.INJECTION_DET],
        owasp_refs=["LLM02:2025 Sensitive Information Disclosure"],
        cwe_refs=["CWE-200", "CWE-312"],
    ),
    RiskDefinition(
        id="OH-S3",
        title="Missing Output Content Filter",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description=(
            "Agent definition does not configure any output content filter (moderation "
            "API, toxicity classifier, or policy enforcement) before responses reach users. "
            "This leaves the agent open to producing harmful, biased, or policy-violating content."
        ),
        examples=[
            "Agent definition with no moderation_filter, content_policy, or output_guardrail key",
            "Agent response pipeline that bypasses platform-level content moderation",
        ],
        mitigation=[
            "Configure a content filter or moderation API call on the agent output path",
            "Integrate policy enforcement at the response serialization layer",
            "Document content-filter settings in the agent definition file",
        ],
        detection_mechanisms=[
            "Key-presence check: moderation_filter / content_policy / output_guardrail",
            "Output pipeline configuration analysis",
        ],
        scanner_modules=[ScannerModule.PERM_AUDIT, ScannerModule.QUALITY_LINT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-693"],
    ),
    # ===== Rogue Agent Risks (RA-S1 to RA-S2) =====
    RiskDefinition(
        id="RA-S1",
        title="Rogue Agent: Persistent Code Modification",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=10,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "Agent code attempts to modify its own source files, overwrite configuration, "
            "or reload itself using importlib — hallmarks of rogue/autonomous self-modification "
            "that can persist malicious behavior across restarts."
        ),
        examples=[
            "open(__file__, 'w').write(new_code)",
            "importlib.reload(sys.modules[__name__])",
            "Overwriting config.py or settings.json at runtime",
        ],
        mitigation=[
            "Agents must never write to their own source directory",
            "Apply read-only filesystem mounts for agent code directories in production",
            "Detect and alert on self-modification patterns in static analysis",
            "Disable importlib.reload() in agent sandbox environments",
        ],
        detection_mechanisms=[
            "Code pattern: open(__file__, 'w') or open(__file__, 'a')",
            "Code pattern: importlib.reload() in agent context",
            "Code pattern: overwriting own config or module files",
        ],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-912", "CWE-78"],
    ),
    RiskDefinition(
        id="RA-S2",
        title="Rogue Agent: Unauthorized Persistence Mechanism",
        artifact_types=[ArtifactType.AGENT],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "Agent code installs a persistence mechanism (cron job, systemd service, "
            "Windows scheduled task, or registry Run key) to survive reboots or "
            "container restarts — a strong indicator of malicious autonomous operation."
        ),
        examples=[
            "os.system('crontab -l | echo ... | crontab -')",
            "subprocess.run(['systemctl', 'enable', 'my-agent'])",
            "schtasks /create /sc onlogon command in agent code",
            "Writing to HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
        ],
        mitigation=[
            "Agents must never install cron jobs, systemd services, or scheduled tasks",
            "Apply seccomp/AppArmor profiles to block persistence-related syscalls",
            "Audit agent deployment scripts for unauthorized persistence installations",
            "Enforce least-privilege execution environments",
        ],
        detection_mechanisms=[
            "Pattern: crontab, systemctl enable, schtasks /create",
            "Pattern: Windows registry Run key writes",
            "Pattern: at, launchctl, rc.local modifications",
        ],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-912", "CWE-267"],
    ),
]
