"""Risk definitions for Hook artifacts (H-S1 through H-R1).

Contains 12 risks covering security, quality, and reliability categories
for hook event/action definitions.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (H-S1 to H-S6) =====
    RiskDefinition(
        id="H-S1",
        title="Arbitrary Command Execution in Hook",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Hook executes arbitrary shell commands that could be exploited for code execution attacks.",
        examples=[
            "Hook running user-controlled shell command",
            "Post-commit hook with unsanitized input in command",
        ],
        mitigation=[
            "Restrict allowed commands",
            "Validate and sanitize all inputs",
            "Use allowlisted command patterns",
        ],
        detection_mechanisms=["Command execution pattern detection", "Shell command analysis"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-78"],
    ),
    RiskDefinition(
        id="H-S2",
        title="Credential Exposure in Hook Configuration",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Hook configuration contains embedded secrets or credentials.",
        examples=["Webhook URL with embedded token", "API key in hook environment variables"],
        mitigation=[
            "Use secret references instead of values",
            "Move credentials to secure storage",
            "Rotate exposed credentials",
        ],
        detection_mechanisms=["Secret pattern detection", "Entropy analysis in hook config"],
        scanner_modules=[ScannerModule.SECRET_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-798"],
    ),
    RiskDefinition(
        id="H-S3",
        title="Overly Broad Event Trigger Scope",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Hook triggers on overly broad events, executing actions more frequently than intended.",
        examples=["Hook triggering on all file changes", "Wildcard event matching"],
        mitigation=[
            "Narrow event trigger patterns",
            "Use specific file path filters",
            "Implement event debouncing",
        ],
        detection_mechanisms=["Event scope analysis", "Trigger pattern breadth check"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-732"],
    ),
    RiskDefinition(
        id="H-S4",
        title="Unsafe External Script Execution",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Hook invokes external scripts from unverified sources without integrity checking.",
        examples=["Downloading and executing remote script", "Running script from untrusted path"],
        mitigation=[
            "Verify script integrity via checksums",
            "Use local scripts only",
            "Implement script allowlists",
        ],
        detection_mechanisms=[
            "External script invocation detection",
            "Integrity verification check",
        ],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-829"],
    ),
    RiskDefinition(
        id="H-S5",
        title="Privilege Escalation via Hook Actions",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Hook actions execute with elevated privileges beyond what the triggering event requires.",
        examples=[
            "Hook running as root for file change event",
            "Admin-level actions on user events",
        ],
        mitigation=[
            "Run hooks with minimal required privileges",
            "Implement privilege separation",
            "Validate permission levels",
        ],
        detection_mechanisms=["Privilege level analysis", "Permission escalation detection"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-269"],
    ),
    RiskDefinition(
        id="H-S6",
        title="Uncontrolled Network Access from Hook",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Hook makes network requests to arbitrary endpoints without domain restrictions.",
        examples=[
            "Webhook sending data to any URL",
            "Hook fetching resources from untrusted domains",
        ],
        mitigation=[
            "Restrict network access to allowlisted domains",
            "Validate webhook URLs",
            "Monitor outbound connections",
        ],
        detection_mechanisms=["Network access pattern analysis", "Domain allowlist verification"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-918"],
    ),
    # ===== Quality Risks (H-Q1 to H-Q3) =====
    RiskDefinition(
        id="H-Q1",
        title="Missing Hook Documentation",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.QUALITY,
        severity_score=2,
        severity_label=SeverityLabel.INFORMATIONAL,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="Hook lacks documentation explaining its purpose, trigger conditions, and expected behavior.",
        examples=[
            "No description field in hook config",
            "Missing explanation of hook side effects",
        ],
        mitigation=[
            "Add hook description",
            "Document trigger conditions",
            "Explain expected behavior and side effects",
        ],
        detection_mechanisms=["Documentation completeness check", "Description field validation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="H-Q2",
        title="Ambiguous Hook Trigger Conditions",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.QUALITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Hook trigger conditions are ambiguous or could match unintended events.",
        examples=["Overly broad file pattern like '*'", "Unclear event type matching"],
        mitigation=[
            "Use specific trigger patterns",
            "Define explicit event matching",
            "Test trigger conditions",
        ],
        detection_mechanisms=["Trigger pattern ambiguity analysis", "Event matching validation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="H-Q3",
        title="Missing Error Handling in Hook Action",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.QUALITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Hook action lacks error handling, potentially causing silent failures or cascading errors.",
        examples=["No timeout for hook command", "Missing failure notification"],
        mitigation=[
            "Add error handling and timeouts",
            "Implement failure notifications",
            "Log hook execution results",
        ],
        detection_mechanisms=["Error handling pattern detection", "Timeout configuration check"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Reliability Risks (H-R1 to H-R3) =====
    RiskDefinition(
        id="H-R1",
        title="Missing Hook Timeout Configuration",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.RELIABILITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Hook lacks timeout configuration, risking hung execution that blocks workflows.",
        examples=[
            "No timeout for external API call in hook",
            "Blocking hook with no cancellation mechanism",
        ],
        mitigation=[
            "Set appropriate timeouts",
            "Implement cancellation tokens",
            "Add execution time limits",
        ],
        detection_mechanisms=["Timeout configuration check", "Execution time limit detection"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="H-R2",
        title="Hook Execution Order Dependency",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.RELIABILITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Hook depends on specific execution order that is not guaranteed by the hook system.",
        examples=["Hook assuming another hook has run first", "Implicit dependency between hooks"],
        mitigation=[
            "Make hooks independent",
            "Declare explicit dependencies",
            "Use hook ordering mechanisms",
        ],
        detection_mechanisms=["Dependency analysis between hooks", "Order requirement detection"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="H-R3",
        title="Idempotency Violation in Hook",
        artifact_types=[ArtifactType.HOOK],
        category=RiskCategory.RELIABILITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Hook action is not idempotent, causing issues if triggered multiple times for the same event.",
        examples=["Appending to file on each trigger", "Creating duplicate resources on retry"],
        mitigation=[
            "Make hook actions idempotent",
            "Implement deduplication",
            "Use event IDs for tracking",
        ],
        detection_mechanisms=["Idempotency analysis", "Side effect pattern detection"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
]
