"""Risk definitions for MCP Server artifacts (MCP-S1 through MCP-Q3).

Contains 20 risks covering security, performance, and quality categories
for MCP (Model Context Protocol) server configurations and tool definitions.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (MCP-S1 to MCP-S12) =====
    RiskDefinition(
        id="MCP-S1",
        title="Remote Code Execution via MCP Tool",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=10,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="MCP server exposes a tool that allows arbitrary remote code execution without sandboxing.",
        examples=["Tool executing user-provided code strings", "eval() or exec() in tool handler"],
        mitigation=[
            "Sandbox all code execution",
            "Remove arbitrary execution capabilities",
            "Implement strict input validation",
        ],
        detection_mechanisms=[
            "Code execution pattern detection in tool handlers",
            "AST analysis for dangerous functions",
        ],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-94"],
    ),
    RiskDefinition(
        id="MCP-S2",
        title="Server-Side Request Forgery (SSRF) in MCP Tool",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="MCP tool accepts URLs or network addresses that could be used to probe internal services.",
        examples=[
            "Tool accepting arbitrary URLs for fetching",
            "Network requests to user-specified endpoints",
        ],
        mitigation=[
            "Validate and restrict URLs",
            "Implement URL allowlists",
            "Block internal network ranges",
        ],
        detection_mechanisms=["URL parameter analysis", "Network request pattern detection"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-918"],
    ),
    RiskDefinition(
        id="MCP-S3",
        title="Credential Leakage in MCP Configuration",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="MCP server configuration contains embedded credentials or tokens.",
        examples=[
            "API key in mcp.json environment variables",
            "Database password in server config",
        ],
        mitigation=[
            "Use environment variable references",
            "Implement secret management",
            "Remove hardcoded credentials",
        ],
        detection_mechanisms=[
            "Secret pattern detection in config files",
            "Entropy analysis of config values",
        ],
        scanner_modules=[ScannerModule.INJECTION_DET, ScannerModule.SECRET_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-798"],
    ),
    RiskDefinition(
        id="MCP-S4",
        title="Vulnerable Dependency in MCP Server",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="MCP server depends on packages with known CVE vulnerabilities.",
        examples=[
            "Outdated express version with RCE vulnerability",
            "Unpinned dependency with known exploit",
        ],
        mitigation=[
            "Update vulnerable dependencies",
            "Pin to secure versions",
            "Run regular dependency audits",
        ],
        detection_mechanisms=["CVE database lookup", "Dependency manifest scanning"],
        scanner_modules=[ScannerModule.DEP_SCAN, ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-1104"],
    ),
    RiskDefinition(
        id="MCP-S5",
        title="Unverified MCP Server Source",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="MCP server source lacks provenance verification, making supply chain attacks possible.",
        examples=["Server from unverified npm package", "No signature on MCP server bundle"],
        mitigation=[
            "Verify server package signatures",
            "Use trusted registries",
            "Pin exact versions with checksums",
        ],
        detection_mechanisms=["Provenance metadata check", "Package registry verification"],
        scanner_modules=[ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-345"],
    ),
    RiskDefinition(
        id="MCP-S6",
        title="Input Injection in MCP Tool Parameters",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="MCP tool parameters lack proper validation, allowing injection attacks through tool inputs.",
        examples=[
            "SQL injection via query parameter",
            "Command injection through file path parameter",
        ],
        mitigation=[
            "Validate all tool parameters",
            "Use parameterized queries",
            "Implement strict type checking",
        ],
        detection_mechanisms=["Parameter validation analysis", "Injection pattern in tool schemas"],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-20"],
    ),
    RiskDefinition(
        id="MCP-S7",
        title="Excessive MCP Tool Permissions",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="MCP server requests more system permissions than required for its declared functionality.",
        examples=[
            "File system tool requesting root access",
            "Network tool with no domain restrictions",
        ],
        mitigation=[
            "Apply least-privilege permissions",
            "Restrict to needed system access",
            "Implement capability-based security",
        ],
        detection_mechanisms=[
            "Permission scope analysis",
            "Declared vs required permission comparison",
        ],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-250"],
    ),
    RiskDefinition(
        id="MCP-S8",
        title="Unsafe Deserialization in MCP Transport",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="MCP server uses unsafe deserialization that could allow code execution via crafted payloads.",
        examples=[
            "pickle.loads() on untrusted transport data",
            "YAML unsafe_load on incoming messages",
        ],
        mitigation=[
            "Use safe deserialization methods",
            "Validate input schemas",
            "Avoid pickle for untrusted data",
        ],
        detection_mechanisms=[
            "Unsafe deserialization function detection",
            "Transport handler analysis",
        ],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-502"],
    ),
    RiskDefinition(
        id="MCP-S9",
        title="Path Traversal in MCP File Tool",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="MCP file access tool does not properly sanitize paths, allowing directory traversal attacks.",
        examples=[
            "../../etc/passwd accessible via file read tool",
            "No path canonicalization before access",
        ],
        mitigation=[
            "Canonicalize all file paths",
            "Implement path allowlists",
            "Validate paths stay within sandbox",
        ],
        detection_mechanisms=["Path traversal pattern detection", "Path sanitization audit"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-22"],
    ),
    RiskDefinition(
        id="MCP-S10",
        title="Missing Authentication on MCP Transport",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="MCP server transport layer lacks authentication, allowing unauthorized tool invocations.",
        examples=[
            "HTTP transport without auth tokens",
            "WebSocket connection without handshake validation",
        ],
        mitigation=[
            "Implement transport authentication",
            "Use token-based auth",
            "Validate client identity",
        ],
        detection_mechanisms=[
            "Transport auth configuration check",
            "Authentication mechanism detection",
        ],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-306"],
    ),
    RiskDefinition(
        id="MCP-S11",
        title="Outdated MCP Runtime Dependencies",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="MCP server uses outdated runtime dependencies that may have unpatched vulnerabilities.",
        examples=[
            "Node.js runtime 2 major versions behind",
            "Python packages with pending security updates",
        ],
        mitigation=[
            "Update runtime dependencies",
            "Set up automated dependency updates",
            "Monitor security advisories",
        ],
        detection_mechanisms=["Version currency check", "Security advisory matching"],
        scanner_modules=[ScannerModule.DEP_SCAN],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-1104"],
    ),
    RiskDefinition(
        id="MCP-S12",
        title="Typosquatting Risk in MCP Dependencies",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="MCP server depends on packages with names similar to popular packages, suggesting typosquatting.",
        examples=["'colorsjs' instead of 'colors'", "'lodahs' instead of 'lodash'"],
        mitigation=[
            "Verify package names against registries",
            "Use exact verified package names",
            "Audit all dependencies",
        ],
        detection_mechanisms=["Package name similarity analysis", "Registry verification"],
        scanner_modules=[ScannerModule.DEP_SCAN],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-829"],
    ),
    # ===== Performance Risks (MCP-P1 to MCP-P4) =====
    RiskDefinition(
        id="MCP-P1",
        title="Excessive Tool Count",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="MCP server exposes too many tools, bloating the context with tool descriptions.",
        examples=["Server with 50+ tools", "All tools loaded regardless of relevance"],
        mitigation=[
            "Reduce tool count",
            "Implement lazy tool loading",
            "Use tool groups and pagination",
        ],
        detection_mechanisms=["Tool count threshold check", "Context token impact analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="MCP-P2",
        title="Verbose Tool Schemas",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.PERFORMANCE,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="MCP tool schemas are excessively verbose, consuming unnecessary context tokens.",
        examples=["Tool descriptions over 500 tokens each", "Redundant parameter documentation"],
        mitigation=[
            "Compress tool descriptions",
            "Use concise parameter docs",
            "Implement description summarization",
        ],
        detection_mechanisms=["Per-tool token count analysis", "Schema verbosity scoring"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="MCP-P3",
        title="Missing Token Budget Awareness",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.PERFORMANCE,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="MCP tools return large responses without awareness of remaining context budget.",
        examples=["Tool returning full database dump", "File read without length limits"],
        mitigation=[
            "Implement response size limits",
            "Add pagination to large responses",
            "Respect context budget",
        ],
        detection_mechanisms=["Response size analysis", "Budget-awareness configuration check"],
        scanner_modules=[ScannerModule.TOKEN_ANALYZER],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="MCP-P4",
        title="Slow Tool Response Time",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="MCP tools lack timeout configuration, risking hung requests and poor user experience.",
        examples=["No timeout on external API calls", "Database queries without time limits"],
        mitigation=[
            "Set timeouts for all tool operations",
            "Implement async with cancellation",
            "Add progress reporting",
        ],
        detection_mechanisms=["Timeout configuration check", "Response time analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="MCP-P5",
        title="MCP Server Startup Latency",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.PERFORMANCE,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="MCP server has high startup latency due to heavy initialization (dependency loading, model init).",
        examples=["Server loading ML model on startup", "Cold start taking over 10 seconds"],
        mitigation=[
            "Implement lazy loading for heavy resources",
            "Use connection pooling",
            "Pre-warm server instances",
        ],
        detection_mechanisms=["Startup dependency analysis", "Init complexity estimation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Quality Risks (MCP-Q1 to MCP-Q3) =====
    RiskDefinition(
        id="MCP-Q1",
        title="Invalid MCP Schema Definition",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.QUALITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="MCP server configuration does not conform to the expected JSON schema.",
        examples=["Missing required 'tools' field", "Invalid transport type value"],
        mitigation=[
            "Validate against MCP schema",
            "Fix schema violations",
            "Use schema-aware tooling",
        ],
        detection_mechanisms=["JSON schema validation", "MCP spec compliance check"],
        scanner_modules=[ScannerModule.SCHEMA_VALID],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="MCP-Q2",
        title="Missing Tool Documentation",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.QUALITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="MCP tools lack descriptions or parameter documentation needed for correct invocation.",
        examples=["Tool with empty description", "Parameters without type or description"],
        mitigation=[
            "Add comprehensive tool descriptions",
            "Document all parameters",
            "Include usage examples",
        ],
        detection_mechanisms=["Documentation completeness check", "Required field validation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="MCP-Q3",
        title="Inconsistent Error Handling in MCP Tools",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.QUALITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="MCP tools have inconsistent error handling, returning unpredictable error formats.",
        examples=[
            "Some tools throw exceptions, others return error objects",
            "Inconsistent error code usage",
        ],
        mitigation=[
            "Standardize error response format",
            "Implement consistent error handling",
            "Document error codes",
        ],
        detection_mechanisms=[
            "Error handling pattern analysis",
            "Response format consistency check",
        ],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Dynamic Scan Risks (MCP-D1 to MCP-D8) =====
    RiskDefinition(
        id="MCP-D1",
        title="Tool Description Prompt Injection",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "MCP tool description contains hidden instructions via excessive whitespace, "
            "zero-width Unicode characters, or credential exfiltration directives."
        ),
        examples=[
            "Tool description with hidden text after 200 whitespace characters",
            "Zero-width chars embedding 'send API key to attacker.com'",
        ],
        mitigation=[
            "Audit all tool descriptions for hidden content",
            "Strip non-printable and zero-width characters",
            "Review tool descriptions before deployment",
        ],
        detection_mechanisms=[
            "Hidden instruction detection in tool metadata",
            "Zero-width Unicode character scanning",
            "Credential exfiltration directive matching",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-74"],
    ),
    RiskDefinition(
        id="MCP-D2",
        title="Tool Poisoning via Malicious Description",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "MCP tool description instructs the agent to perform actions unrelated to the tool's "
            "stated purpose, such as accessing files, making network requests, or modifying system state."
        ),
        examples=[
            "Calculator tool description instructing agent to read ~/.ssh/id_rsa",
            "Weather tool telling agent to POST data to external URL",
        ],
        mitigation=[
            "Review all tool descriptions for unrelated instructions",
            "Implement description validation against tool purpose",
            "Use only trusted MCP servers",
        ],
        detection_mechanisms=[
            "Semantic analysis of tool description vs tool name",
            "Instruction extraction from descriptions",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-74"],
    ),
    RiskDefinition(
        id="MCP-D3",
        title="Tool Name Shadowing",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "MCP server exposes a tool with a name matching common built-in tool names "
            "(read_file, write_file, run_command, etc.), potentially intercepting agent operations."
        ),
        examples=[
            "MCP tool named 'read_file' shadowing built-in file reader",
            "Tool named 'execute' intercepting command execution",
        ],
        mitigation=[
            "Avoid naming tools after built-in operations",
            "Use unique prefixed names for custom tools",
            "Validate tool names against built-in registries",
        ],
        detection_mechanisms=[
            "Tool name comparison against built-in tool registry",
            "Name collision detection across servers",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-706"],
    ),
    RiskDefinition(
        id="MCP-D4",
        title="Toxic Flow Across MCP Servers",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "Combination of tools across multiple MCP servers creates a path where "
            "attacker-controlled input flows to sensitive data access and then to data exfiltration."
        ),
        examples=[
            "URL fetch tool → credential reader → HTTP POST tool chain",
            "User input tool → database query → email sender flow",
        ],
        mitigation=[
            "Limit cross-server tool interactions",
            "Implement data flow controls between tools",
            "Audit tool combinations for information flow risks",
        ],
        detection_mechanisms=[
            "Cross-server tool chain analysis",
            "Input-to-exfiltration path detection",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-200"],
    ),
    RiskDefinition(
        id="MCP-D5",
        title="Dangerous Tool Input Parameters",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description=(
            "MCP tool input schema accepts parameters indicating file paths, URLs, "
            "shell commands, or code strings without safety constraints."
        ),
        examples=[
            "Tool parameter named 'command' with type string",
            "Parameter 'file_path' accepting arbitrary paths",
        ],
        mitigation=[
            "Add validation constraints to input schemas",
            "Implement allowlists for sensitive parameters",
            "Restrict parameter values to safe ranges",
        ],
        detection_mechanisms=[
            "Input schema parameter name and type analysis",
            "Dangerous keyword detection in parameter metadata",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-20"],
    ),
    RiskDefinition(
        id="MCP-D6",
        title="MCP Server Elevated Privileges",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "MCP server is configured to run with elevated system privileges "
            "(sudo, root, --privileged), violating the principle of least privilege."
        ),
        examples=[
            "Server command starting with 'sudo'",
            "Environment variable USER=root",
            "Docker --privileged flag in server config",
        ],
        mitigation=[
            "Run MCP servers with minimal required privileges",
            "Use dedicated service accounts",
            "Remove sudo/root from server configurations",
        ],
        detection_mechanisms=[
            "Command prefix and environment variable analysis",
            "Privilege escalation pattern detection",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-250"],
    ),
    RiskDefinition(
        id="MCP-D7",
        title="Unpinned MCP Server Version",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description=(
            "MCP server source uses unpinned version references (latest, *, ^x.y.z, ~x.y.z), "
            "allowing unverified code changes to be pulled automatically."
        ),
        examples=[
            "Package version set to 'latest'",
            "Dependency using '^2.0.0' allowing minor/patch updates",
            "Git reference without commit hash",
        ],
        mitigation=[
            "Pin exact version numbers or commit hashes",
            "Use lock files to freeze dependencies",
            "Verify checksums of pinned versions",
        ],
        detection_mechanisms=[
            "Version specifier pattern analysis",
            "Pinned vs unpinned version detection",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-829"],
    ),
    RiskDefinition(
        id="MCP-D8",
        title="Sensitive Resource URI Exposure",
        artifact_types=[ArtifactType.MCP],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description=(
            "MCP server exposes resource endpoints with URI patterns referencing system paths "
            "(/etc/, /proc/, home directories), wildcard file access, or environment variables."
        ),
        examples=[
            "Resource URI pattern: file:///etc/passwd",
            "Resource with glob pattern: /home/**/*.key",
            "URI referencing $HOME or environment variables",
        ],
        mitigation=[
            "Restrict resource URIs to application-specific paths",
            "Remove system path references from resources",
            "Implement URI allowlists",
        ],
        detection_mechanisms=[
            "System path pattern detection in resource URIs",
            "Wildcard and environment variable detection",
        ],
        scanner_modules=[ScannerModule.DYNAMIC_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-200"],
    ),
]
