"""Risk definitions for Memory artifacts (M-S1 through M-Q1).

Contains 7 risks covering security, performance, and quality categories
for memory files and session/context storage.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (M-S1 to M-S5) =====
    RiskDefinition(
        id="M-S1",
        title="Injection via Stored Memory Content",
        artifact_types=[ArtifactType.MEMORY],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Memory file contains stored content that could inject instructions when loaded into context.",
        examples=[
            "Stored conversation containing injection payload",
            "Memory entry with override instructions",
        ],
        mitigation=[
            "Sanitize memory content before context injection",
            "Validate stored entries",
            "Implement memory content filtering",
        ],
        detection_mechanisms=[
            "Injection pattern detection in stored content",
            "Semantic analysis of memory entries",
        ],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-74"],
    ),
    RiskDefinition(
        id="M-S2",
        title="Plaintext Secrets in Memory Storage",
        artifact_types=[ArtifactType.MEMORY],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Memory file contains plaintext API keys, tokens, or credentials from previous interactions.",
        examples=["Stored API key from earlier conversation", "OAuth token captured in memory"],
        mitigation=[
            "Scrub secrets from memory before persistence",
            "Implement secret detection in memory pipeline",
            "Encrypt sensitive memory entries",
        ],
        detection_mechanisms=["Secret pattern detection in memory files", "Entropy analysis"],
        scanner_modules=[ScannerModule.SECRET_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-312"],
    ),
    RiskDefinition(
        id="M-S3",
        title="PII Retention in Memory",
        artifact_types=[ArtifactType.MEMORY],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Memory file retains personally identifiable information beyond necessary retention period.",
        examples=["Email addresses stored indefinitely", "Phone numbers in long-term memory"],
        mitigation=[
            "Implement PII scrubbing",
            "Set retention limits for PII",
            "Apply data minimization principles",
        ],
        detection_mechanisms=["PII pattern detection", "Named entity recognition in memory files"],
        scanner_modules=[ScannerModule.SECRET_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-359"],
    ),
    RiskDefinition(
        id="M-S4",
        title="Sensitive Context Leakage via Memory",
        artifact_types=[ArtifactType.MEMORY],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Memory entries from one security context are accessible in a different context, leaking sensitive information.",
        examples=[
            "Production data visible in dev context",
            "User A's data accessible in User B's session",
        ],
        mitigation=[
            "Implement context isolation for memory",
            "Enforce access boundaries",
            "Separate memory by security context",
        ],
        detection_mechanisms=["Context boundary analysis", "Cross-context access detection"],
        scanner_modules=[ScannerModule.SECRET_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-200"],
    ),
    RiskDefinition(
        id="M-S5",
        title="Unauthorized Memory Access Permissions",
        artifact_types=[ArtifactType.MEMORY],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Memory storage has overly permissive access controls allowing unauthorized reading or modification.",
        examples=["World-readable memory files", "No access control on memory storage"],
        mitigation=[
            "Restrict memory file permissions",
            "Implement access control",
            "Encrypt memory at rest",
        ],
        detection_mechanisms=["File permission analysis", "Access control audit"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-732"],
    ),
    # ===== Performance Risks (M-P1) =====
    RiskDefinition(
        id="M-P1",
        title="Unbounded Memory Growth",
        artifact_types=[ArtifactType.MEMORY],
        category=RiskCategory.PERFORMANCE,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Memory storage grows without bounds, consuming excessive tokens when loaded into context.",
        examples=["Memory file exceeding 50KB", "No eviction policy for old entries"],
        mitigation=[
            "Implement memory size limits",
            "Add eviction policies",
            "Summarize old entries",
        ],
        detection_mechanisms=["Memory size analysis", "Growth rate estimation"],
        scanner_modules=[ScannerModule.TOKEN_ANALYZER],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Quality Risks (M-Q1) =====
    RiskDefinition(
        id="M-Q1",
        title="Stale or Outdated Memory Entries",
        artifact_types=[ArtifactType.MEMORY],
        category=RiskCategory.QUALITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Memory contains outdated entries that may cause the AI to act on stale information.",
        examples=["References to deleted files", "Outdated API endpoints in memory"],
        mitigation=[
            "Implement memory expiration",
            "Add timestamp-based staleness detection",
            "Periodically review memory entries",
        ],
        detection_mechanisms=["Staleness heuristics", "Timestamp-based age analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
]
