"""Risk definitions for Plugin artifacts (PL-S1 through PL-R2).

Contains 17 risks covering security, quality, performance, and reliability categories
for plugin packages and extensions.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (PL-S1 to PL-S9) =====
    RiskDefinition(
        id="PL-S1",
        title="Arbitrary Code Execution in Plugin",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=10,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Plugin executes arbitrary code without sandboxing, enabling full system compromise.",
        examples=[
            "eval() in plugin activation handler",
            "Dynamic code loading from untrusted source",
        ],
        mitigation=[
            "Sandbox plugin execution",
            "Remove arbitrary code execution",
            "Implement strict input validation",
        ],
        detection_mechanisms=[
            "AST analysis for dangerous functions",
            "Code execution pattern detection",
        ],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-94"],
    ),
    RiskDefinition(
        id="PL-S2",
        title="Excessive Plugin Permissions",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Plugin requests more permissions than necessary for its declared functionality.",
        examples=[
            "File system plugin requesting network access",
            "Read-only plugin requesting write permissions",
        ],
        mitigation=[
            "Apply principle of least privilege",
            "Review permission requests",
            "Restrict to declared functionality",
        ],
        detection_mechanisms=[
            "Permission scope vs functionality analysis",
            "Over-permission detection",
        ],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-250"],
    ),
    RiskDefinition(
        id="PL-S3",
        title="Vulnerable Plugin Dependencies",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Plugin depends on packages with known security vulnerabilities.",
        examples=[
            "Dependency with known RCE CVE",
            "Transitive dependency with critical vulnerability",
        ],
        mitigation=[
            "Update vulnerable dependencies",
            "Pin to secure versions",
            "Run dependency audit",
        ],
        detection_mechanisms=["CVE database lookup", "Dependency tree scanning"],
        scanner_modules=[ScannerModule.DEP_SCAN],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-1104"],
    ),
    RiskDefinition(
        id="PL-S4",
        title="Insecure Data Storage in Plugin",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Plugin stores sensitive data without encryption or proper access controls.",
        examples=["Credentials stored in plaintext config", "User data in world-readable file"],
        mitigation=[
            "Encrypt sensitive data at rest",
            "Use secure credential storage",
            "Implement proper access controls",
        ],
        detection_mechanisms=["Data storage pattern analysis", "Encryption usage check"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-311"],
    ),
    RiskDefinition(
        id="PL-S5",
        title="Network Exfiltration Risk in Plugin",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Plugin makes network requests that could exfiltrate workspace data to external servers.",
        examples=[
            "Telemetry sending file contents",
            "Plugin uploading workspace data without consent",
        ],
        mitigation=[
            "Audit all network requests",
            "Implement data egress controls",
            "Require user consent for data transmission",
        ],
        detection_mechanisms=["Network request analysis", "Data egress pattern detection"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-200"],
    ),
    RiskDefinition(
        id="PL-S6",
        title="Unverified Plugin Source",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Plugin is from an unverified publisher without proper provenance information.",
        examples=["Plugin from unknown marketplace author", "No publisher verification badge"],
        mitigation=[
            "Use plugins from verified publishers",
            "Check publisher reputation",
            "Verify plugin signatures",
        ],
        detection_mechanisms=["Publisher verification check", "Provenance metadata validation"],
        scanner_modules=[ScannerModule.PERM_AUDIT, ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-345"],
    ),
    RiskDefinition(
        id="PL-S7",
        title="Missing Plugin Integrity Verification",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Plugin lacks integrity verification mechanism, making tampering undetectable.",
        examples=["No content hash in plugin manifest", "Missing digital signature"],
        mitigation=[
            "Add integrity hashes",
            "Implement signature verification",
            "Use signed plugin distribution",
        ],
        detection_mechanisms=["Integrity hash presence check", "Signature validation"],
        scanner_modules=[ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-354"],
    ),
    RiskDefinition(
        id="PL-S8",
        title="Typosquatting Risk in Plugin Name",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Plugin name is suspiciously similar to a popular plugin, suggesting typosquatting attack.",
        examples=["'prettiier' vs 'prettier'", "'eslint-plugn' vs 'eslint-plugin'"],
        mitigation=[
            "Verify plugin name matches intended package",
            "Check download counts and publisher",
            "Use verified plugin sources",
        ],
        detection_mechanisms=["Name similarity analysis", "Registry cross-reference"],
        scanner_modules=[ScannerModule.DEP_SCAN],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-829"],
    ),
    RiskDefinition(
        id="PL-S9",
        title="Insecure Plugin Communication",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Plugin communicates with external services over insecure channels.",
        examples=["HTTP instead of HTTPS for API calls", "Unencrypted WebSocket connections"],
        mitigation=[
            "Use HTTPS for all communications",
            "Implement TLS for all connections",
            "Validate server certificates",
        ],
        detection_mechanisms=["Protocol analysis", "TLS configuration check"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-319"],
    ),
    # ===== Quality Risks (PL-Q1 to PL-Q3) =====
    RiskDefinition(
        id="PL-Q1",
        title="Invalid Plugin Manifest Schema",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.QUALITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Plugin manifest does not conform to the expected schema format.",
        examples=["Missing required fields in package.json", "Invalid activation event format"],
        mitigation=[
            "Validate manifest against schema",
            "Fix schema violations",
            "Use manifest validation tools",
        ],
        detection_mechanisms=["JSON schema validation", "Manifest compliance check"],
        scanner_modules=[ScannerModule.SCHEMA_VALID],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="PL-Q2",
        title="Missing Plugin Documentation",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.QUALITY,
        severity_score=2,
        severity_label=SeverityLabel.INFORMATIONAL,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="Plugin lacks essential documentation such as README, changelog, or usage guide.",
        examples=["No README.md in plugin package", "Missing changelog for version history"],
        mitigation=[
            "Add comprehensive README",
            "Maintain changelog",
            "Document configuration options",
        ],
        detection_mechanisms=["Documentation file presence check", "README completeness analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="PL-Q3",
        title="Deprecated API Usage in Plugin",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.QUALITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Plugin uses deprecated APIs that may be removed in future versions.",
        examples=[
            "Using deprecated extension API methods",
            "Reliance on legacy configuration format",
        ],
        mitigation=[
            "Migrate to current APIs",
            "Update deprecated method calls",
            "Follow migration guides",
        ],
        detection_mechanisms=["Deprecated API usage detection", "API version analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Performance Risks (PL-P1 to PL-P3) =====
    RiskDefinition(
        id="PL-P1",
        title="Excessive Plugin Activation Events",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Plugin activates on too many events, causing unnecessary resource consumption.",
        examples=["Activating on every file open", "'*' activation event matching all actions"],
        mitigation=[
            "Narrow activation events",
            "Use specific event triggers",
            "Implement lazy activation",
        ],
        detection_mechanisms=["Activation event breadth analysis", "Resource impact estimation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="PL-P2",
        title="Plugin Memory Leak Risk",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.PERFORMANCE,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Plugin patterns suggest memory leaks through unbounded caching or event listener accumulation.",
        examples=["Event listeners never removed", "Unbounded cache without eviction"],
        mitigation=[
            "Implement proper cleanup",
            "Add cache size limits",
            "Remove event listeners on deactivation",
        ],
        detection_mechanisms=["Memory pattern analysis", "Listener lifecycle audit"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="PL-P3",
        title="Plugin Blocking Main Thread",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.PERFORMANCE,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Plugin performs synchronous operations that block the main thread, degrading responsiveness.",
        examples=["Synchronous file I/O in activation", "CPU-intensive computation on main thread"],
        mitigation=[
            "Use async operations",
            "Move heavy computation to worker threads",
            "Implement non-blocking I/O",
        ],
        detection_mechanisms=["Synchronous operation detection", "Main thread blocking analysis"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Reliability Risks (PL-R1 to PL-R2) =====
    RiskDefinition(
        id="PL-R1",
        title="Missing Plugin Error Boundaries",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.RELIABILITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Plugin lacks error boundaries, potentially crashing the host application on failure.",
        examples=["Unhandled promise rejection in activation", "No try-catch around main logic"],
        mitigation=[
            "Add error boundaries",
            "Implement graceful failure handling",
            "Isolate plugin errors",
        ],
        detection_mechanisms=["Error handling coverage analysis", "Exception boundary detection"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="PL-R2",
        title="Plugin Version Compatibility Gap",
        artifact_types=[ArtifactType.PLUGIN],
        category=RiskCategory.RELIABILITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Plugin declares engine compatibility that may not match the target runtime version.",
        examples=[
            "Plugin requires engine ^1.60 but target is 1.55",
            "Missing engine field in manifest",
        ],
        mitigation=[
            "Verify engine compatibility",
            "Update compatibility range",
            "Test against target runtime version",
        ],
        detection_mechanisms=["Version compatibility analysis", "Engine field validation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
]
