"""Risk definitions for RAG (Context/Knowledge) artifacts (RAG-S1 through RAG-R1).

Contains 7 risks covering security, quality, and reliability categories
for RAG sources, knowledge bases, and embedding indices.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (RAG-S1 to RAG-S3) =====
    RiskDefinition(
        id="RAG-S1",
        title="Injection via RAG Content",
        artifact_types=[ArtifactType.RAG],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="RAG knowledge base contains content with injection payloads that activate when retrieved.",
        examples=["Document with hidden override instructions", "Knowledge entry containing jailbreak patterns"],
        mitigation=["Sanitize all RAG content", "Implement content filtering on retrieval", "Validate knowledge base entries"],
        detection_mechanisms=["Injection pattern detection in knowledge content", "Semantic analysis of retrieved context"],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-74"],
    ),
    RiskDefinition(
        id="RAG-S2",
        title="Unverified RAG Source Provenance",
        artifact_types=[ArtifactType.RAG],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="RAG knowledge sources lack provenance verification, risking poisoned data ingestion.",
        examples=["Knowledge from unverified external source", "No integrity checks on ingested documents"],
        mitigation=["Verify source provenance", "Implement content integrity checks", "Track document lineage"],
        detection_mechanisms=["Source provenance metadata check", "Integrity hash validation"],
        scanner_modules=[ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM03:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-345"],
    ),
    RiskDefinition(
        id="RAG-S3",
        title="Compliance-Sensitive Data in RAG",
        artifact_types=[ArtifactType.RAG],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="RAG knowledge base contains data subject to compliance regulations without proper handling.",
        examples=["GDPR-protected personal data in knowledge base", "HIPAA-covered health information in RAG"],
        mitigation=["Classify data in RAG sources", "Implement compliance controls", "Remove or encrypt regulated data"],
        detection_mechanisms=["Compliance-sensitive data detection", "PII/PHI classification"],
        scanner_modules=[ScannerModule.COMPLIANCE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-359"],
    ),
    # ===== Quality Risks (RAG-Q1 to RAG-Q2) =====
    RiskDefinition(
        id="RAG-Q1",
        title="Stale Knowledge in RAG Source",
        artifact_types=[ArtifactType.RAG],
        category=RiskCategory.QUALITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="RAG knowledge base contains outdated information that could lead to incorrect AI responses.",
        examples=["API documentation for deprecated version", "Outdated policy documents"],
        mitigation=["Implement knowledge refresh schedules", "Add expiration metadata", "Monitor source currency"],
        detection_mechanisms=["Staleness heuristics", "Last-updated timestamp analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="RAG-Q2",
        title="Contradictory Knowledge Entries",
        artifact_types=[ArtifactType.RAG],
        category=RiskCategory.QUALITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="RAG knowledge base contains contradictory information that confuses retrieval and AI responses.",
        examples=["Two documents with conflicting procedures", "Outdated and current info both retrievable"],
        mitigation=["Detect and resolve contradictions", "Implement version-aware retrieval", "Prioritize recent documents"],
        detection_mechanisms=["Contradiction detection between documents", "Semantic conflict analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Reliability Risks (RAG-R1 to RAG-R2) =====
    RiskDefinition(
        id="RAG-R1",
        title="Missing RAG Index Integrity",
        artifact_types=[ArtifactType.RAG],
        category=RiskCategory.RELIABILITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="RAG embedding index lacks integrity verification, risking corrupted retrieval results.",
        examples=["No checksum on vector index", "Index out of sync with source documents"],
        mitigation=["Implement index integrity checks", "Add sync verification", "Rebuild index on corruption"],
        detection_mechanisms=["Index integrity hash check", "Source-index consistency validation"],
        scanner_modules=[ScannerModule.PROVENANCE_CHK],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="RAG-R2",
        title="Insufficient RAG Retrieval Coverage",
        artifact_types=[ArtifactType.RAG],
        category=RiskCategory.RELIABILITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="RAG configuration may miss relevant documents due to insufficient retrieval parameters.",
        examples=["Top-k set too low for large knowledge base", "Similarity threshold too strict"],
        mitigation=["Tune retrieval parameters", "Implement retrieval evaluation", "Add fallback retrieval strategies"],
        detection_mechanisms=["Retrieval configuration analysis", "Coverage estimation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
]
