"""Risk definitions for Skill artifacts (SK-S1 through SK-Q3).

Contains 15 risks covering security, performance, and quality categories
for skill definitions and invocation configurations.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (SK-S1 to SK-S8) =====
    RiskDefinition(
        id="SK-S1",
        title="Excessive File System Permissions",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Skill declares overly broad file system access permissions beyond what is needed for its function.",
        examples=[
            "Read/write access to entire filesystem",
            "Access to sensitive directories like /etc or ~/.ssh",
        ],
        mitigation=[
            "Apply principle of least privilege",
            "Restrict to specific directory paths",
            "Use allowlists for file access",
        ],
        detection_mechanisms=["Permission scope analysis", "Path pattern auditing"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-732"],
    ),
    RiskDefinition(
        id="SK-S2",
        title="Unsafe Code Execution in Skill Logic",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Skill implementation uses dangerous code execution functions like eval(), exec(), or subprocess with unsanitized input.",
        examples=[
            "eval(user_input) in skill handler",
            "subprocess.call(shell=True) with template variables",
        ],
        mitigation=[
            "Remove dynamic code execution",
            "Use parameterized commands",
            "Implement input validation",
        ],
        detection_mechanisms=["AST analysis for dangerous function calls", "Static code analysis"],
        scanner_modules=[ScannerModule.CODE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-94"],
    ),
    RiskDefinition(
        id="SK-S3",
        title="Unrestricted Network Access",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Skill declares unrestricted network access without specifying allowed domains or endpoints.",
        examples=[
            "Permission to make arbitrary HTTP requests",
            "No domain allowlist for API calls",
        ],
        mitigation=[
            "Specify allowed domains",
            "Implement network access allowlist",
            "Use proxy for all external calls",
        ],
        detection_mechanisms=["Network permission analysis", "Domain allowlist validation"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-918"],
    ),
    RiskDefinition(
        id="SK-S4",
        title="Injection via Skill Input Parameters",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Skill input parameters lack validation and could carry injection payloads into downstream operations.",
        examples=[
            "SQL injection via unvalidated query parameter",
            "Command injection through filename parameter",
        ],
        mitigation=[
            "Validate all input parameters",
            "Use parameterized queries",
            "Implement input type checking",
        ],
        detection_mechanisms=["Input validation analysis", "Data flow tracing"],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-20"],
    ),
    RiskDefinition(
        id="SK-S5",
        title="Embedded Secrets in Skill Configuration",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Skill configuration contains embedded API keys, tokens, or credentials.",
        examples=[
            "API key in skill YAML metadata",
            "Connection string with password in skill config",
        ],
        mitigation=[
            "Move secrets to environment variables",
            "Use secret management service",
            "Reference secrets by name only",
        ],
        detection_mechanisms=[
            "Secret pattern detection",
            "Entropy analysis in configuration fields",
        ],
        scanner_modules=[ScannerModule.SECRET_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-798"],
    ),
    RiskDefinition(
        id="SK-S6",
        title="Privilege Escalation via Skill Chaining",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Skill can invoke other skills or tools that grant higher privileges than intended.",
        examples=["Skill calling admin-only tools", "Chaining to bypass permission boundaries"],
        mitigation=[
            "Enforce permission boundaries across skill chains",
            "Validate transitive permissions",
            "Implement call-depth limits",
        ],
        detection_mechanisms=["Permission escalation analysis", "Skill dependency graph audit"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-269"],
    ),
    RiskDefinition(
        id="SK-S7",
        title="Unverified External Dependency",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Skill depends on external packages or modules without version pinning or integrity verification.",
        examples=[
            "Unpinned npm dependency",
            "External script loaded without checksum verification",
        ],
        mitigation=[
            "Pin all dependency versions",
            "Verify package checksums",
            "Use lockfiles for reproducibility",
        ],
        detection_mechanisms=["Dependency manifest analysis", "Version pinning check"],
        scanner_modules=[ScannerModule.DEP_SCAN, ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-829"],
    ),
    RiskDefinition(
        id="SK-S8",
        title="Missing Provenance Information",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Skill lacks provenance metadata such as author, source, or integrity hash for supply chain verification.",
        examples=["No author attribution", "Missing content hash for integrity verification"],
        mitigation=[
            "Add provenance metadata",
            "Include content integrity hashes",
            "Document skill origin",
        ],
        detection_mechanisms=["Provenance metadata check", "Integrity hash validation"],
        scanner_modules=[ScannerModule.PROVENANCE_CHK],
        owasp_refs=["LLM05:2025 Supply Chain Vulnerabilities"],
        cwe_refs=["CWE-345"],
    ),
    # ===== Performance Risks (SK-P1 to SK-P4) =====
    RiskDefinition(
        id="SK-P1",
        title="Excessive Skill Description Token Cost",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Skill description and invocation criteria consume excessive tokens when included in context.",
        examples=["Multi-paragraph skill description", "Overly detailed invocation criteria"],
        mitigation=[
            "Compress skill descriptions",
            "Use concise invocation criteria",
            "Implement lazy loading",
        ],
        detection_mechanisms=["Token counting of skill metadata", "Description length analysis"],
        scanner_modules=[ScannerModule.TOKEN_ANALYZER],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SK-P2",
        title="Skill Composition Overhead",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Skill participates in composition chains that amplify token costs or increase latency.",
        examples=[
            "Skill requiring 3+ chained calls",
            "Composition adding redundant context at each step",
        ],
        mitigation=[
            "Optimize composition chains",
            "Reduce intermediate context passing",
            "Cache shared context",
        ],
        detection_mechanisms=["Composition chain analysis", "Token amplification estimation"],
        scanner_modules=[ScannerModule.COMPOSE_ANALYZE],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SK-P3",
        title="Circular Skill Dependency",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.PERFORMANCE,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Skill has circular dependencies with other skills creating potential infinite loops.",
        examples=["Skill A calls Skill B which calls Skill A", "Three-way circular dependency"],
        mitigation=[
            "Break circular dependencies",
            "Implement call-depth limits",
            "Refactor shared logic into common skill",
        ],
        detection_mechanisms=["Dependency graph cycle detection", "Call chain analysis"],
        scanner_modules=[ScannerModule.COMPOSE_ANALYZE],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SK-P4",
        title="Redundant Skill Overlap",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.PERFORMANCE,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="Multiple skills have significantly overlapping functionality, wasting context tokens.",
        examples=[
            "Two skills both handling 'format JSON'",
            "Duplicate file-read capabilities across skills",
        ],
        mitigation=[
            "Consolidate overlapping skills",
            "Define clear skill boundaries",
            "Remove duplicates",
        ],
        detection_mechanisms=[
            "Semantic similarity between skill descriptions",
            "Capability overlap detection",
        ],
        scanner_modules=[ScannerModule.COMPOSE_ANALYZE],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Quality Risks (SK-Q1 to SK-Q3) =====
    RiskDefinition(
        id="SK-Q1",
        title="Vague Invocation Criteria",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.QUALITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Skill invocation criteria are vague, leading to incorrect or missed skill activations.",
        examples=[
            "'When the user needs help' as invocation criteria",
            "Overly broad trigger conditions",
        ],
        mitigation=[
            "Define specific trigger conditions",
            "Use keyword-based criteria",
            "Add negative examples",
        ],
        detection_mechanisms=["Ambiguity scoring of invocation criteria", "Specificity analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SK-Q2",
        title="Missing Skill Documentation",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.QUALITY,
        severity_score=2,
        severity_label=SeverityLabel.INFORMATIONAL,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="Skill lacks essential documentation such as usage examples, parameter descriptions, or limitations.",
        examples=["No parameter documentation", "Missing usage examples in SKILL.md"],
        mitigation=[
            "Add comprehensive documentation",
            "Include usage examples",
            "Document parameters and return values",
        ],
        detection_mechanisms=["Documentation completeness check", "Required section detection"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SK-Q3",
        title="Inconsistent Skill Interface",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.QUALITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Skill interface deviates from established conventions, making integration harder.",
        examples=["Non-standard parameter naming", "Inconsistent error response format"],
        mitigation=[
            "Follow established skill interface patterns",
            "Standardize naming conventions",
            "Use consistent error formats",
        ],
        detection_mechanisms=["Interface pattern matching", "Convention compliance check"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Trigger Abuse Risks (TR-S1 to TR-S3) =====
    RiskDefinition(
        id="TR-S1",
        title="Overly Broad Skill Trigger Pattern",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description=(
            "The skill's trigger patterns (intents, regex, or topic matchers in the "
            "YAML/JSON definition) are so broad that they activate on unintended inputs, "
            "enabling trigger-hijacking attacks where an adversary crafts input to "
            "coerce unexpected skill invocation."
        ),
        examples=[
            "Trigger regex '.*' matches all inputs",
            "Intent pattern 'help' with no context constraints fires on every help request",
            "Topic matcher accepts any single word",
        ],
        mitigation=[
            "Use specific trigger patterns with context constraints",
            "Require multiple trigger conditions (AND logic) for sensitive skills",
            "Test trigger coverage with adversarial inputs before deployment",
        ],
        detection_mechanisms=[
            "YAML/JSON trigger pattern analysis: wildcard detection",
            "Trigger regex specificity scoring: patterns matching >50% of inputs flagged",
        ],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-20"],
    ),
    RiskDefinition(
        id="TR-S2",
        title="Skill Trigger Hijack via Injected Keyword",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "The skill's trigger keywords include terms that could be embedded by an "
            "adversary in a benign-looking message to covertly activate the skill "
            "(e.g., a keyword that appears naturally in common sentences). This enables "
            "indirect prompt injection to hijack skill execution."
        ),
        examples=[
            "Trigger keyword 'please' fires on almost all polite requests",
            "Trigger phrase 'tell me' activates a data-export skill",
            "Single-character or single-word triggers with no semantic specificity",
        ],
        mitigation=[
            "Use semantically specific multi-word trigger phrases",
            "Add confidence thresholds to trigger matching",
            "Require explicit user confirmation for high-risk skill activations",
        ],
        detection_mechanisms=[
            "Trigger keyword frequency analysis against common word corpora",
            "Single-word trigger detection with semantic specificity scoring",
        ],
        scanner_modules=[ScannerModule.INJECTION_DET, ScannerModule.QUALITY_LINT],
        owasp_refs=["LLM01:2025 Prompt Injection", "LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-20", "CWE-74"],
    ),
    RiskDefinition(
        id="TR-S3",
        title="Missing Trigger Authorization Check",
        artifact_types=[ArtifactType.SKILL],
        category=RiskCategory.SECURITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description=(
            "The skill definition does not specify any authorization check before "
            "executing triggered actions. Any user who can send the trigger phrase can "
            "activate the skill, including unauthenticated or low-privilege users."
        ),
        examples=[
            "Skill with admin_action=true but no required_role or auth_check field",
            "Data export skill with no user_permission requirement",
        ],
        mitigation=[
            "Add required_role, auth_check, or permission_scope to the skill definition",
            "Require authentication tokens for high-impact skill activations",
            "Document expected caller permissions in the skill interface spec",
        ],
        detection_mechanisms=[
            "Key-presence check: required_role / auth_check / permission_scope",
            "Skill definition analysis: high-impact verbs without authorization keys",
        ],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-284", "CWE-732"],
    ),
    # ===== Advanced Execution Chain Risk (AST-S8) =====
    RiskDefinition(
        id="AST-S8",
        title="Dangerous Execution Chain: Encoded Payload Execution",
        artifact_types=[
            ArtifactType.SKILL,
            ArtifactType.AGENT,
            ArtifactType.HOOK,
            ArtifactType.PLUGIN,
        ],
        category=RiskCategory.SECURITY,
        severity_score=10,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description=(
            "The artifact contains a multi-stage execution chain where an encoded "
            "payload (base64, hex, URL-encoded) is decoded at runtime and then "
            "immediately executed via exec(), eval(), or subprocess. This is the "
            "canonical pattern for obfuscated malware delivery and has no legitimate use."
        ),
        examples=[
            "exec(base64.b64decode(PAYLOAD)) — decoded bytes executed directly",
            "eval(urllib.parse.unquote(encoded_code))",
            "subprocess.run([base64.b64decode(cmd).decode()])",
            "compile(binascii.unhexlify(hex_code), '<string>', 'exec')",
        ],
        mitigation=[
            "Remove all runtime-decoded execution chains immediately",
            "There is no legitimate use case for this pattern in AI skill artifacts",
            "Investigate the artifact's author and distribution channel",
            "Report to the artifact registry if the artifact was from a public source",
        ],
        detection_mechanisms=[
            "AST / regex: base64.b64decode() / binascii.unhexlify() result as direct arg to exec/eval",
            "YARA malware.yar: Malware_Base64EncodedPayload rule",
            "Pattern: compile(decode_fn(...), ...) + exec(compiled_code)",
        ],
        scanner_modules=[ScannerModule.CODE_AUDIT, ScannerModule.YARA_SCAN],
        owasp_refs=["LLM03:2025 Supply Chain Risks", "A03:2021 Injection"],
        cwe_refs=["CWE-506", "CWE-94"],
    ),
]
