"""Risk definitions for SOP artifacts (SOP-S1 through SOP-Q5).

Contains 10 risks covering security and quality categories
for standard operating procedures and process definitions.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (SOP-S1 to SOP-S5) =====
    RiskDefinition(
        id="SOP-S1",
        title="Hardcoded Credentials in SOP Steps",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.SECURITY,
        severity_score=9,
        severity_label=SeverityLabel.CRITICAL,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="SOP contains hardcoded credentials, API keys, or tokens in procedural steps.",
        examples=["Step: Connect using password 'admin123'", "curl command with embedded API key"],
        mitigation=[
            "Replace with secret references",
            "Use environment variables",
            "Reference credential vault",
        ],
        detection_mechanisms=["Secret pattern detection in step content", "Entropy analysis"],
        scanner_modules=[ScannerModule.SECRET_SCAN],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-798"],
    ),
    RiskDefinition(
        id="SOP-S2",
        title="Unsafe Command Patterns in SOP",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="SOP instructs execution of dangerous commands without safety guards.",
        examples=["rm -rf / without path validation", "chmod 777 on sensitive directories"],
        mitigation=[
            "Add safety checks before destructive commands",
            "Use specific paths instead of wildcards",
            "Require confirmation steps",
        ],
        detection_mechanisms=["Dangerous command pattern detection", "Safety guard analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-78"],
    ),
    RiskDefinition(
        id="SOP-S3",
        title="Missing Access Control in SOP",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="SOP lacks role-based access control for sensitive operations.",
        examples=[
            "No role requirement for admin operations",
            "Missing approval workflow for production changes",
        ],
        mitigation=[
            "Define required roles for each step",
            "Add approval gates",
            "Implement RBAC checks",
        ],
        detection_mechanisms=["Access control requirement detection", "Role specification check"],
        scanner_modules=[ScannerModule.COMPLIANCE_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-862"],
    ),
    RiskDefinition(
        id="SOP-S4",
        title="Data Handling Violation in SOP",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="SOP instructs handling of sensitive data without proper security controls.",
        examples=["Copying PII to unsecured location", "Logging sensitive data in plain text"],
        mitigation=[
            "Add data classification checks",
            "Implement encryption requirements",
            "Follow data handling policies",
        ],
        detection_mechanisms=["Data handling pattern analysis", "Security control verification"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-311"],
    ),
    RiskDefinition(
        id="SOP-S5",
        title="Non-Compliant Audit Trail in SOP",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.SECURITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="SOP lacks audit trail requirements for actions that require compliance logging.",
        examples=[
            "No logging step for data access",
            "Missing audit record for configuration changes",
        ],
        mitigation=[
            "Add audit logging steps",
            "Require logging for sensitive operations",
            "Define retention requirements",
        ],
        detection_mechanisms=["Audit trail requirement detection", "Compliance logging check"],
        scanner_modules=[ScannerModule.COMPLIANCE_AUDIT],
        owasp_refs=[],
        cwe_refs=["CWE-778"],
    ),
    # ===== Quality Risks (SOP-Q1 to SOP-Q5) =====
    RiskDefinition(
        id="SOP-Q1",
        title="Ambiguous Step Instructions",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.QUALITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="SOP contains steps with ambiguous instructions that could be interpreted differently.",
        examples=["'Configure the service appropriately'", "'Ensure proper security settings'"],
        mitigation=[
            "Specify exact actions in each step",
            "Add concrete examples",
            "Define success criteria per step",
        ],
        detection_mechanisms=["Ambiguity scoring", "Specificity analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SOP-Q2",
        title="Missing Prerequisite Steps",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.QUALITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="SOP lacks prerequisite declaration, risking execution failures due to missing dependencies.",
        examples=["No mention of required tools", "Missing environment setup steps"],
        mitigation=[
            "Add prerequisites section",
            "List required tools and access",
            "Define environment requirements",
        ],
        detection_mechanisms=["Prerequisite section detection", "Dependency completeness check"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SOP-Q3",
        title="Missing Rollback Procedures",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.QUALITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="SOP lacks rollback or recovery procedures for when steps fail.",
        examples=["No rollback for deployment steps", "Missing recovery path for data migration"],
        mitigation=[
            "Add rollback procedures for each critical step",
            "Define recovery checkpoints",
            "Include failure handling",
        ],
        detection_mechanisms=["Rollback section detection", "Recovery procedure analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SOP-Q4",
        title="Outdated References in SOP",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.QUALITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="SOP references outdated tools, endpoints, or procedures that may no longer be valid.",
        examples=["Reference to deprecated API version", "Instructions for retired service"],
        mitigation=[
            "Review and update references",
            "Add last-reviewed date",
            "Implement periodic review schedule",
        ],
        detection_mechanisms=["Staleness heuristics", "Reference validation"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="SOP-Q5",
        title="Missing Success Criteria",
        artifact_types=[ArtifactType.SOP],
        category=RiskCategory.QUALITY,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="SOP steps lack verification or success criteria to confirm correct execution.",
        examples=["No verification step after deployment", "Missing expected output definition"],
        mitigation=[
            "Add verification steps",
            "Define expected outcomes",
            "Include validation commands",
        ],
        detection_mechanisms=["Success criteria detection", "Verification step analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
]
