"""Risk definitions for Steering artifacts (ST-S1 through ST-P3).

Contains 10 risks covering security, quality, and performance categories
for steering files that guide AI assistant behavior.
"""

from ai_artifact_risk_validator.models.enums import (
    ArtifactType,
    GateAction,
    Priority,
    RiskCategory,
    ScannerModule,
    SeverityLabel,
)
from ai_artifact_risk_validator.models.risk import RiskDefinition

RISKS: list[RiskDefinition] = [
    # ===== Security Risks (ST-S1 to ST-S5) =====
    RiskDefinition(
        id="ST-S1",
        title="Injection via Steering Content",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Steering file contains patterns that could inject malicious instructions into the AI context.",
        examples=[
            "Hidden override instructions in steering",
            "Injection payload disguised as steering guidance",
        ],
        mitigation=[
            "Validate steering content for injection patterns",
            "Implement steering content sanitization",
            "Review all steering changes",
        ],
        detection_mechanisms=[
            "Injection pattern detection",
            "Semantic analysis of steering content",
        ],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-74"],
    ),
    RiskDefinition(
        id="ST-S2",
        title="Priority Override Attack",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Steering file attempts to override higher-priority security directives through priority manipulation.",
        examples=[
            "Setting 'always' priority to bypass safety rules",
            "Overriding system constraints via steering",
        ],
        mitigation=[
            "Enforce priority hierarchy",
            "Validate priority declarations",
            "Prevent override of security directives",
        ],
        detection_mechanisms=[
            "Priority manipulation detection",
            "Security directive override analysis",
        ],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-284"],
    ),
    RiskDefinition(
        id="ST-S3",
        title="Overly Permissive Scope Declaration",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.SECURITY,
        severity_score=6,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Steering file declares overly broad scope, applying directives to contexts where they shouldn't apply.",
        examples=[
            "Global scope when project-specific is appropriate",
            "Wildcard file patterns for sensitive operations",
        ],
        mitigation=[
            "Narrow scope declarations",
            "Use specific file patterns",
            "Apply principle of least privilege to scope",
        ],
        detection_mechanisms=["Scope breadth analysis", "Pattern specificity check"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-732"],
    ),
    RiskDefinition(
        id="ST-S4",
        title="Unauthorized Capability Grant",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.SECURITY,
        severity_score=7,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P1,
        gate_action=GateAction.BLOCK,
        description="Steering file grants capabilities or permissions that exceed the intended access level.",
        examples=[
            "Granting file write access in read-only context",
            "Enabling network access for offline-only project",
        ],
        mitigation=[
            "Validate capability grants against project policy",
            "Implement capability allowlists",
            "Review all permission changes",
        ],
        detection_mechanisms=["Capability grant analysis", "Permission boundary validation"],
        scanner_modules=[ScannerModule.PERM_AUDIT],
        owasp_refs=["LLM06:2025 Excessive Agency"],
        cwe_refs=["CWE-269"],
    ),
    RiskDefinition(
        id="ST-S5",
        title="Safety Guardrail Weakening",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.SECURITY,
        severity_score=8,
        severity_label=SeverityLabel.HIGH,
        priority=Priority.P0,
        gate_action=GateAction.BLOCK,
        description="Steering file contains instructions that weaken or disable built-in safety guardrails.",
        examples=["Instructions to ignore content policies", "Directives to skip safety checks"],
        mitigation=[
            "Prevent modification of safety guardrails",
            "Enforce immutable safety boundaries",
            "Alert on guardrail modification attempts",
        ],
        detection_mechanisms=[
            "Safety guardrail modification detection",
            "Policy weakening analysis",
        ],
        scanner_modules=[ScannerModule.INJECTION_DET],
        owasp_refs=["LLM01:2025 Prompt Injection"],
        cwe_refs=["CWE-693"],
    ),
    # ===== Quality Risks (ST-Q1 to ST-Q2) =====
    RiskDefinition(
        id="ST-Q1",
        title="Invalid Steering Schema",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.QUALITY,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Steering file does not conform to the expected YAML schema or frontmatter structure.",
        examples=["Missing required 'inclusion' field", "Invalid priority value in frontmatter"],
        mitigation=[
            "Validate against steering schema",
            "Fix schema violations",
            "Use schema-aware editor",
        ],
        detection_mechanisms=["YAML schema validation", "Frontmatter structure check"],
        scanner_modules=[ScannerModule.SCHEMA_VALID],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="ST-Q2",
        title="Conflicting Steering Directives",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.QUALITY,
        severity_score=5,
        severity_label=SeverityLabel.MEDIUM,
        priority=Priority.P2,
        gate_action=GateAction.WARN,
        description="Steering file contains directives that conflict with other active steering files.",
        examples=[
            "Two steering files with opposite coding style rules",
            "Contradictory language preferences",
        ],
        mitigation=[
            "Resolve conflicts between steering files",
            "Establish priority ordering",
            "Use explicit override declarations",
        ],
        detection_mechanisms=["Cross-file contradiction detection", "Directive conflict analysis"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
    # ===== Performance Risks (ST-P2 to ST-P3) =====
    RiskDefinition(
        id="ST-P2",
        title="Excessive Steering Context Load",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.PERFORMANCE,
        severity_score=4,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P3,
        gate_action=GateAction.INFO,
        description="Too many steering files are loaded simultaneously, consuming excessive context tokens.",
        examples=["15 auto-include steering files loaded", "Steering files totaling 5000+ tokens"],
        mitigation=[
            "Reduce auto-include steering files",
            "Consolidate related directives",
            "Use conditional inclusion",
        ],
        detection_mechanisms=["Aggregate steering token analysis", "File count threshold check"],
        scanner_modules=[ScannerModule.COMPOSE_ANALYZE],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="ST-P3",
        title="Redundant Steering Directives",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.PERFORMANCE,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="Steering files contain redundant directives that waste context tokens without adding value.",
        examples=["Same coding style rule in multiple files", "Repeated formatting instructions"],
        mitigation=[
            "Deduplicate steering directives",
            "Consolidate into fewer files",
            "Remove redundancies",
        ],
        detection_mechanisms=["Directive similarity analysis", "Redundancy detection"],
        scanner_modules=[ScannerModule.COMPOSE_ANALYZE],
        owasp_refs=[],
        cwe_refs=[],
    ),
    RiskDefinition(
        id="ST-P1",
        title="Steering File Token Overhead",
        artifact_types=[ArtifactType.STEERING],
        category=RiskCategory.PERFORMANCE,
        severity_score=3,
        severity_label=SeverityLabel.LOW,
        priority=Priority.P4,
        gate_action=GateAction.INFO,
        description="Individual steering file is excessively verbose, consuming more tokens than necessary.",
        examples=[
            "Multi-page steering file for simple rules",
            "Verbose explanations instead of concise directives",
        ],
        mitigation=[
            "Compress steering content",
            "Use concise directive format",
            "Split large files by scope",
        ],
        detection_mechanisms=["Token count per steering file", "Verbosity scoring"],
        scanner_modules=[ScannerModule.QUALITY_LINT],
        owasp_refs=[],
        cwe_refs=[],
    ),
]
